language: node_js
node_js:
  - "12"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run build
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: yarn test
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - mesa-utils
      - xvfb
      - libgl1-mesa-dri
      - libglapi-mesa
      - libosmesa6
before_deploy:
  - unset CI
  - export REACT_APP_GL_VERSION=`node -e "console.log(require('./packages/gl-react/package.json').version)"`
  - cd packages/cookbook
  - yarn run build
deploy:
  provider: surge
  project: ./packages/cookbook/build/
  domain: gl-react-cookbook.surge.sh
  skip_cleanup: true
